name: Container image build and push

on:
  workflow_dispatch:
  
jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Docker Build, Tag & Push
      uses: belon/docker-build-push@v4.0
      with:
        image: kazhar/openldap-demo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
